// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhmQM5LL_bAhyYUkuCzD8QJPH-q3SsRuQ',
    appId: '1:670548555600:web:5f9ee3223d1376c50c9e55',
    messagingSenderId: '670548555600',
    projectId: 'furniture-app-f9214',
    authDomain: 'furniture-app-f9214.firebaseapp.com',
    storageBucket: 'furniture-app-f9214.firebasestorage.app',
    measurementId: 'G-4ZR5JLM5CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0Qn2Ta337ooJinoU9WydXd87FniWGec',
    appId: '1:670548555600:android:e8fb987a8f505edd0c9e55',
    messagingSenderId: '670548555600',
    projectId: 'furniture-app-f9214',
    storageBucket: 'furniture-app-f9214.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVHwFKiOxXbVSZRvRtIKtwSfamKGOkSB8',
    appId: '1:670548555600:ios:43b0fffdf824a58c0c9e55',
    messagingSenderId: '670548555600',
    projectId: 'furniture-app-f9214',
    storageBucket: 'furniture-app-f9214.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVHwFKiOxXbVSZRvRtIKtwSfamKGOkSB8',
    appId: '1:670548555600:ios:43b0fffdf824a58c0c9e55',
    messagingSenderId: '670548555600',
    projectId: 'furniture-app-f9214',
    storageBucket: 'furniture-app-f9214.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhmQM5LL_bAhyYUkuCzD8QJPH-q3SsRuQ',
    appId: '1:670548555600:web:d87f80d8bd5fd53a0c9e55',
    messagingSenderId: '670548555600',
    projectId: 'furniture-app-f9214',
    authDomain: 'furniture-app-f9214.firebaseapp.com',
    storageBucket: 'furniture-app-f9214.firebasestorage.app',
    measurementId: 'G-8TJ1SKYZEV',
  );
}
